import { Container } from "inversify";
import { TYPES } from "./types";
import { IRolService } from '../interfaces/IRol.service'; 
import { RolService } from '../services/Rol.service'; 
import { AdministradorService } from '../services/Administrador.service'
import { CredencialesService } from "../services/Credenciales.service";
import { IGrupoOcupacionalService } from '../interfaces/IGrupoOcupacional.service';
import { GrupoOcupacionalService } from "../services/GrupoOcupacional.service";
import { ProfesionService } from "../services/Ocupacion.service";
import { ISolicitanteService } from '../interfaces/ISolicitante.service';
import { SolicitanteService } from "../services/Solicitante.service";
import { EmpleadorService } from "../services/Empleador.service"; 
import { CurriculumService } from "../services/Curriculum.service";
import { ICurriculumService } from '../interfaces/ICurriculum.service';
import { ReferenciaService } from "../services/Referencia.service";
import { IdiomaService } from "../services/Idioma.service";
import { CurriculumIdiomaService } from "../services/CurriculumIdioma.service";
import { INivelIdiomaService } from '../interfaces/INivelIdioma.service';
import { NivelIdiomaService } from "../services/Nivel-idioma.service";
import { IEstadoCivilService } from '../interfaces/IEstadoCivil.service';
import { EstadoCivilService } from "../services/EstadoCivil.service";
import { ImagenService } from "../services/Imagen.service";
import { HabilidadService } from "../services/Habilidad.service";
import { CurriculumHabilidadService } from "../services/CurriculumHabilidad.service";
import { ICurriculumHabilidadService } from '../interfaces/ICurriculumHabilidad.service';
import { ExperienciaService } from "../services/Experiencia.service";
import { INivelEstudioService } from '../interfaces/INivelEstudio.service';
import { NivelEstudioService } from "../services/Nivel-estudio.service";
import { GradoEscolarService } from "../services/GradoEscolar.service";
import { IGradoEscolarService } from '../interfaces/IGradoEscolar.service';
import { EstudioBasicoService } from "../services/estudio-basico.service";
import { IEstudioBasicoService } from '../interfaces/IEstudioBasico.service';
import { IEstudioAvanzadoService } from '../interfaces/IEstudioAvanzado.service';
import { EstudioAvanzadoService } from "../services/EstudioAvanzado.service";
import { EmpresaService } from "../services/Empresa.service";
import { ITipoContratoService } from '../interfaces/ITipoContrato.service';
import { TipoContratoService } from "../services/TipoContrato.service";
import { IRangoSueldoService } from '../interfaces/IRangoSueldo.service';
import { RangoSueldoService } from "../services/Rango-sueldo.service";
import { IVacanteService } from '../interfaces/IVacante.service';
import { VacanteService } from "../services/Vacante.service";
import { HorarioService } from "../services/Horario.service";
import { PostulacionService } from "../services/Postulacion.service";
import { ContratacionService } from "../services/Contratacion.service";
import { PaisService } from "../services/Pais.service";
import { IPaisService } from '../interfaces/IPais.service';
import { EstadoService } from "../services/Estado.service";
import { IEstadoService } from '../interfaces/IEstado.service';
import { CiudadService } from "../services/Ciudad.service";
import { IOcupacionSolicitanteService } from '../interfaces/IOcupacionSolicitante.service';
import { OcupacionSolicitanteService } from "../services/Ocupacion-solicitante.service";
import { INotificacionEmpleadorService } from '../interfaces/INotificacionEmpleador.service';
import { NotificacionEmpleadorService } from "../services/Notificacion-empleador.service";
import { INotificacionSolicitanteService } from '../interfaces/INotificacionSolicitante.service';
import { NotificacionSolicitanteService } from "../services/Notificacion-solicitante.service";
import { IReportesSolicitanteService } from '../interfaces/IReportes-solicitante.service';
import { ReportesSolicitanteService } from "../services/Reportes-solicitante.service";
import { ReportesContratacionService } from "../services/Reportes-contratacion.service";
import { IReportesContratacionService } from '../interfaces/IReportes-contratacion.service';
import { IReportesVacanteService } from '../interfaces/IReportes-vacante.service';
import { ReportesVacanteService } from "../services/Reportes-vacante.service";
import { IReportesEmpleadorService } from '../interfaces/IReportes-empleador.service';
import { ReportesEmpleadorService } from "../services/Reportes-empleador.service";
import { IAdministradorService } from '../interfaces/IAdministrador.service';
import { ICredencialesService } from '../interfaces/ICreadenciales.service';
import { IOcupacionService } from '../interfaces/IOcupacion.service';
import { IEmpleadorService } from '../interfaces/IEmpleador.service';
import { IReferenciaService } from '../interfaces/IReferencias.service';
import { IIdiomaService } from '../interfaces/IIdioma.service';
import { ICurriculumIdiomaService } from '../interfaces/ICurriculum-idioma.service';
import { IHabilidadService } from '../interfaces/IHabilidad.service';
import { IImagenService } from '../interfaces/IImagen.service';
import { IExperienciaService } from '../interfaces/IExperiencia.service';
import { IEmpresaService } from '../interfaces/IEmpresa.service';
import { IHorarioService } from '../interfaces/IHorario.service';
import { IPostulacionService } from '../interfaces/IPostulacion.service';
import { IContratacionService } from '../interfaces/IContratacion.service';
import { ICiudadService } from '../interfaces/ICiudad.service';
import { IReportePostulacionesService } from '../interfaces/IReporte-postulaciones.service';
import { ReportePostulacionesService } from "../services/Reporte-portulaciones.service";
import { IInformacionAppService } from '../interfaces/IInformacionApp.service';
import { InformacionAppService } from "../services/InformacionApp.service";

const myContainer = new Container();

myContainer.bind<IRolService>(TYPES.IRolService).to(RolService);
myContainer.bind<IAdministradorService>(TYPES.IAdministradorService).to(AdministradorService); 
myContainer.bind<ICredencialesService>(TYPES.ICredencialesService).to(CredencialesService);
myContainer.bind<IGrupoOcupacionalService>(TYPES.IGrupoOcupacionalService).to(GrupoOcupacionalService);
myContainer.bind<IOcupacionService>(TYPES.IOcupacionService).to(ProfesionService);  
myContainer.bind<ISolicitanteService>(TYPES.ISolicitanteService).to(SolicitanteService);  
myContainer.bind<IEmpleadorService>(TYPES.IEmpleadorService).to(EmpleadorService); 
myContainer.bind<ICurriculumService>(TYPES.ICurriculumService).to(CurriculumService);
myContainer.bind<IReferenciaService>(TYPES.IReferenciaService).to(ReferenciaService);
myContainer.bind<IIdiomaService>(TYPES.IIdiomaService).to(IdiomaService);
myContainer.bind<ICurriculumIdiomaService>(TYPES.ICurriculumIdiomaService).to(CurriculumIdiomaService);
myContainer.bind<INivelIdiomaService>(TYPES.INivelIdiomaService).to(NivelIdiomaService);
myContainer.bind<IEstadoCivilService>(TYPES.IEstadoCivilService).to(EstadoCivilService);
myContainer.bind<IImagenService>(TYPES.IImagenService).to(ImagenService);
myContainer.bind<IHabilidadService>(TYPES.IHabilidadService).to(HabilidadService);
myContainer.bind<ICurriculumHabilidadService>(TYPES.ICurriculumHabilidadService).to(CurriculumHabilidadService);
myContainer.bind<IExperienciaService>(TYPES.IExperienciaService).to(ExperienciaService);
myContainer.bind<INivelEstudioService>(TYPES.INivelEstudioService).to(NivelEstudioService);
myContainer.bind<IGradoEscolarService>(TYPES.IGradoEscolarService).to(GradoEscolarService);
myContainer.bind<IEstudioBasicoService>(TYPES.IEstudioBasicoService).to(EstudioBasicoService);
myContainer.bind<IEstudioAvanzadoService>(TYPES.IEstudioAvanzadoService).to(EstudioAvanzadoService);
myContainer.bind<IEmpresaService>(TYPES.IEmpresaService).to(EmpresaService);
myContainer.bind<ITipoContratoService>(TYPES.ITipoContratoService).to(TipoContratoService);
myContainer.bind<IRangoSueldoService>(TYPES.IRangoSueldoService).to(RangoSueldoService);
myContainer.bind<IVacanteService>(TYPES.IVacanteService).to(VacanteService);
myContainer.bind<IHorarioService>(TYPES.IHorarioService).to(HorarioService);
myContainer.bind<IPostulacionService>(TYPES.IPostulacionService).to(PostulacionService);
myContainer.bind<IContratacionService>(TYPES.IContratacionService).to(ContratacionService);
myContainer.bind<IPaisService>(TYPES.IPaisService).to(PaisService);
myContainer.bind<IEstadoService>(TYPES.IEstadoService).to(EstadoService);
myContainer.bind<ICiudadService>(TYPES.ICiudadService).to(CiudadService);
myContainer.bind<IOcupacionSolicitanteService>(TYPES.IOcupacionSolicitanteService).to(OcupacionSolicitanteService);
myContainer.bind<INotificacionEmpleadorService>(TYPES.INotificacionEmpleadorService).to(NotificacionEmpleadorService);
myContainer.bind<INotificacionSolicitanteService>(TYPES.INotificacionSolicitanteService).to(NotificacionSolicitanteService);
myContainer.bind<IReportesSolicitanteService>(TYPES.IReportesSolicitanteService).to(ReportesSolicitanteService);
myContainer.bind<IReportesContratacionService>(TYPES.IReportesContratacionService).to(ReportesContratacionService);
myContainer.bind<IReportesVacanteService>(TYPES.IReportesVacanteService).to(ReportesVacanteService);
myContainer.bind<IReportesEmpleadorService>(TYPES.IReportesEmpleadorService).to(ReportesEmpleadorService);
myContainer.bind<IReportePostulacionesService>(TYPES.IReportePostulacionesService).to(ReportePostulacionesService);
myContainer.bind<IInformacionAppService>(TYPES.IInformacionAppService).to(InformacionAppService);

export { myContainer };     