import { Container } from "inversify";
import { TYPES } from "./types";
import { IRolService } from '../src/interfaces/rol.service'; 
import { RolService } from '../src/services/rol.service'; 
import { IAdministradorService } from '../src/interfaces/administrador.service';
import { AdministradorService } from '../src/services/administrador.service'
import { ICredencialesService } from '../src/interfaces/creadenciales.service';
import { CredencialesService } from "../src/services/credenciales.service";
import { IGrupoOcupacionalService } from '../src/interfaces/grupo-ocupacional.service';
import { GrupoOcupacionalService } from "../src/services/grupo-ocupacional";
import { IOcupacionService } from '../src/interfaces/ocupacion.service';
import { ProfesionService } from "../src/services/ocupacion.service";
import { ISolicitanteService } from '../src/interfaces/solicitante.service';
import { SolicitanteService } from "../src/services/solicitante.service";
import { IEmpleadorService } from '../src/interfaces/empleador.service';
import { EmpleadorService } from "../src/services/empleador.service"; 
import { CurriculumService } from "../src/services/curriculum.service";
import { ICurriculumService } from '../src/interfaces/curriculum.service';
import { IReferenciaService } from '../src/interfaces/referencias.service';
import { ReferenciaService } from "../src/services/referencia.service";
import { IIdiomaService } from '../src/interfaces/idioma.service';
import { IdiomaService } from "../src/services/idioma.service";
import { ICurriculumIdiomaService } from '../src/interfaces/curriculum-idioma.service';
import { CurriculumIdiomaService } from "../src/services/curriculum-idioma.service";
import { INivelIdiomaService } from '../src/interfaces/nivel-idioma.service';
import { NivelIdiomaService } from "../src/services/nivel-idioma.service";
import { IEstadoCivilService } from '../src/interfaces/estado-civil.service';
import { EstadoCivilService } from "../src/services/estado-civil.service";
import { IImagenService } from '../src/interfaces/imagen.service';
import { ImagenService } from "../src/services/imagen.service";
import { IHabilidadService } from '../src/interfaces/habilidad.service';
import { HabilidadService } from "../src/services/habilidad.service";
import { CurriculumHabilidadService } from "../src/services/curriculum-habilidad.service";
import { ICurriculumHabilidadService } from '../src/interfaces/curriculum-habilidad.service';
import { IExperienciaService } from '../src/interfaces/experiencia.service';
import { ExperienciaService } from "../src/services/experiencia.service";
import { INivelEstudioService } from '../src/interfaces/nivel-estudio.service';
import { NivelEstudioService } from "../src/services/nivel-estudio.service";
import { GradoEscolarService } from "../src/services/grado-escolar.service";
import { IGradoEscolarService } from '../src/interfaces/grado-escolar.service';
import { EstudioBasicoService } from "../src/services/estudio-basico.service";
import { IEstudioBasicoService } from '../src/interfaces/estudio-basico.service';
import { IEstudioAvanzadoService } from '../src/interfaces/estudio-avanzado.service';
import { EstudioAvanzadoService } from "../src/services/estudio-avanzado.service";
import { IEmpresaService } from '../src/interfaces/empresa.service';
import { EmpresaService } from "../src/services/empresa.service";
import { ITipoContratoService } from '../src/interfaces/tipo-contrato.service';
import { TipoContratoService } from "../src/services/tipo-contrato.service";
import { IRangoSueldoService } from '../src/interfaces/rango-sueldo.service';
import { RangoSueldoService } from "../src/services/rango-sueldo.service";
import { IVacanteService } from '../src/interfaces/vacante.service';
import { VacanteService } from "../src/services/vacante.service";
import { IHorarioService } from '../src/interfaces/horario.service';
import { HorarioService } from "../src/services/horario.service";
import { IPostulacionService } from '../src/interfaces/postulacion.service';
import { PostulacionService } from "../src/services/postulacion.service";
import { IContratacionService } from '../src/interfaces/contratacion.service';
import { ContratacionService } from "../src/services/contratacion.service";
import { PaisService } from "../src/services/pais.service";
import { IPaisService } from '../src/interfaces/pais.service';
import { EstadoService } from "../src/services/estado.service";
import { IEstadoService } from '../src/interfaces/estado.service';
import { CiudadService } from "../src/services/ciudad.service";
import { ICiudadService } from '../src/interfaces/ciudad.service';
import { IOcupacionSolicitanteService } from '../src/interfaces/ocupacion-solicitante.service';
import { OcupacionSolicitanteService } from "../src/services/ocupacion-solicitante.service";

const myContainer = new Container();

myContainer.bind<IRolService>(TYPES.IRolService).to(RolService);
myContainer.bind<IAdministradorService>(TYPES.IAdministradorService).to(AdministradorService); 
myContainer.bind<ICredencialesService>(TYPES.ICredencialesService).to(CredencialesService);
myContainer.bind<IGrupoOcupacionalService>(TYPES.IGrupoOcupacionalService).to(GrupoOcupacionalService);
myContainer.bind<IOcupacionService>(TYPES.IOcupacionService).to(ProfesionService);  
myContainer.bind<ISolicitanteService>(TYPES.ISolicitanteService).to(SolicitanteService);  
myContainer.bind<IEmpleadorService>(TYPES.IEmpleadorService).to(EmpleadorService); 
myContainer.bind<ICurriculumService>(TYPES.ICurriculumService).to(CurriculumService);
myContainer.bind<IReferenciaService>(TYPES.IReferenciaService).to(ReferenciaService);
myContainer.bind<IIdiomaService>(TYPES.IIdiomaService).to(IdiomaService);
myContainer.bind<ICurriculumIdiomaService>(TYPES.ICurriculumIdiomaService).to(CurriculumIdiomaService);
myContainer.bind<INivelIdiomaService>(TYPES.INivelIdiomaService).to(NivelIdiomaService);
myContainer.bind<IEstadoCivilService>(TYPES.IEstadoCivilService).to(EstadoCivilService);
myContainer.bind<IImagenService>(TYPES.IImagenService).to(ImagenService);
myContainer.bind<IHabilidadService>(TYPES.IHabilidadService).to(HabilidadService);
myContainer.bind<ICurriculumHabilidadService>(TYPES.ICurriculumHabilidadService).to(CurriculumHabilidadService);
myContainer.bind<IExperienciaService>(TYPES.IExperienciaService).to(ExperienciaService);
myContainer.bind<INivelEstudioService>(TYPES.INivelEstudioService).to(NivelEstudioService);
myContainer.bind<IGradoEscolarService>(TYPES.IGradoEscolarService).to(GradoEscolarService);
myContainer.bind<IEstudioBasicoService>(TYPES.IEstudioBasicoService).to(EstudioBasicoService);
myContainer.bind<IEstudioAvanzadoService>(TYPES.IEstudioAvanzadoService).to(EstudioAvanzadoService);
myContainer.bind<IEmpresaService>(TYPES.IEmpresaService).to(EmpresaService);
myContainer.bind<ITipoContratoService>(TYPES.ITipoContratoService).to(TipoContratoService);
myContainer.bind<IRangoSueldoService>(TYPES.IRangoSueldoService).to(RangoSueldoService);
myContainer.bind<IVacanteService>(TYPES.IVacanteService).to(VacanteService);
myContainer.bind<IHorarioService>(TYPES.IHorarioService).to(HorarioService);
myContainer.bind<IPostulacionService>(TYPES.IPostulacionService).to(PostulacionService);
myContainer.bind<IContratacionService>(TYPES.IContratacionService).to(ContratacionService);
myContainer.bind<IPaisService>(TYPES.IPaisService).to(PaisService);
myContainer.bind<IEstadoService>(TYPES.IEstadoService).to(EstadoService);
myContainer.bind<ICiudadService>(TYPES.ICiudadService).to(CiudadService);
myContainer.bind<IOcupacionSolicitanteService>(TYPES.IOcupacionSolicitanteService).to(OcupacionSolicitanteService);
export { myContainer };       